INSERT INTO breeds (name)
VALUES 
  ('Labrador Retriever'),
  ('German Shepherd'),
  ('Golden Retriever'),
  ('French Bulldog'),
  ('Bulldog'),
  ('Poodle'),
  ('Beagle'),
  ('Rottweiler'),
  ('Labrador Retriever'),
  ('German Shorthaired'),
  ('Pembroke Welsh Corgi'),
  ('Dachshund'),
  ('Yorkshire Terrier'),
  ('Australian Shepherd'),
  ('Boxer'),
  ('Siberian Husky'),
  ('Pomeranian'),
  ('Great Dane'),
  ('Miniature Schnauzer'),
  ('Doberman Pinscher'),
  ('Shih Tzu'),
  ('Chihuahua'),
  ('English Cocker Spaniel'),
  ('Pug'),
  ('Sheltie'),
  ('Dalmation'),
  ('Basset Hound'),
  ('Border Collie'),
  ('St. Bernard'),
  ('Boston Terrier'),
  ('Alaskan Malamute'),
  ('Mixed-Breed');
