DROP TABLE IF EXISTS dogs_breeds CASCADE;

CREATE TABLE dogs_breeds (
  id SERIAL PRIMARY KEY NOT NULL,
  FOREIGN KEY (dog_id) REFERENCES dogs(id) NOT NULL,
  FOREIGN KEY (breed_id) REFERENCES breeds(id) NOT NULL
);