DROP TABLE IF EXISTS likes CASCADE;

CREATE TABLE likes (
  id SERIAL PRIMARY KEY NOT NULL,
  FOREIGN KEY (liked_by_user_id) REFERENCES users(id) NOT NULL,
  FOREIGN KEY (liked_user_id) REFERENCES users(id) NOT NULL
);